aplikacja/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('publish/', views.publish, name="publish"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplikacja.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplikacja/models.py
from django.db import models
from django.conf import settings


class Publication(models.Model):
    title = models.CharField(max_length=30)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    headline = models.CharField(max_length=100)
    publications = models.ManyToManyField(Publication)

    class Meta:
        ordering = ['headline']

    def __str__(self):
        return self.headline

aplikacja/views.py
from django.shortcuts import render
from .models import Publication, Article

def index(request):
    context = {'index':'Index!'}
    return render(request, 'aplikacja/index.html', context)

def publish(request):
    pubs = Publication.objects.all()
    arts = Article.objects.all()
    context = {'pubs':pubs, 'arts':arts}
    return render(request, 'aplikacja/publication.html', context)

aplikacja/templates/aplikacja/index.html
{% extends 'base.html' %}


{% block content %}
    <a href="{% url 'publish' %}">Publish</a>

    <p class="test">{{ index }}</p>

{% endblock %}

aplikacja/templates/aplikacja/publication.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<ul>
    <h2>Publication</h2>
    {% for pub in pubs %}
        <li>{{ pub }} : 
            <ul>
            {% comment %} {% for art in arts %} {% endcomment %}
                <li>{{ pub.article_set.all }}</li>
            {% comment %} {% endfor %} {% endcomment %}
            <ul>
        </li>
        <p></p>
    {% endfor %}
</ul>

<p></p>
<hr/>

<ul>
    <h2>Article</h2>
    {% for art in arts %}
        <li>
        {{ art }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  </head>
  <body>
    

    <div class="container text-center">
        <div class="row">
          <div class="col">
           {% block content %}
           {% endblock %}
          </div>
        </div>
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>